development:
  adapter: postgresql
  database: redmine_development
  encoding: utf8
 
production:
  adapter: postgresql
  database: redmine_production
  username: redmine-prod
  encoding: utf8

test:
  adapter: postgresql
  database: redmine_test
  username: redmine-test
  encoding: utf8
